apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
  namespace: bar-test
spec:
  resourceSelectors: 
    - apiVersion: apps/v1    
      kind: Deployment
  placement:
    clusterAffinity:
      clusterNames:
        - member1
