apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-bar
  labels:
    app: foo
    mode: bar
spec:
  replicas: 6
  selector:
    matchLabels:
      app: foo
      mode: bar
  template:
    metadata:
      labels:
        app: foo
        mode: bar
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
